### ISSUE TITLE
Error when running gatsby build

### ISSUE THREAD

**Issue by tallman5** [aaronpowell/react-app-insights#3]
Hi Aaron, love the post (and App Insights!) Trying to implement with a blank Gatsby app. Followed your steps from Part 1. Works fine with Gatsby develop. However, I can't get Gatsby build to work. First error was `webpackerror: referenceerror: XMLHttpRequest is not defined`. Followed [this](https://stackoverflow.com/questions/32604460/xmlhttprequest-module-not-defined-found). Now getting an error `cannot read property constructor` on `export default function withAITracking` in node_modules/@microsoft/applicationinsights-react-js/dist-esm/withAITracking.js:16:1.

Any ideas? Thanks again!

**Comment by aaronpowell** [comment]
Hmm, I thought I fixed that error when doing it (some of the stuff didn't like the server side rendering).

Let me check if there's some outdated dependencies.

**Comment by tallman5** [comment]
So, got the `gatsby build` to work, went back to clean blank Gatsby project and added `@microsoft/applicationinsights-web`. Then, updated `layout.js` with the following.

```
import React from "react"
import { ApplicationInsights } from '@microsoft/applicationinsights-web'

const Layout = (props) => {
    let ai = null
    if (typeof window !== "undefined") {
        ai = new ApplicationInsights({
            config: {
                instrumentationKey: process.env.APPINSIGHTS_KEY,
            }
        })
        ai.loadAppInsights()
        console.log("Loaded AI")
    }

    return (
        <div>
            ...
        </div>
    )
}

export default Layout
export const appInsights = ai?.appInsights || null
```

However, cannot correctly implement the `window !== "undefined"` check _and_ log all pages to AI. It currently logs only the first `GET` to AI, none of the other pages while clicking around.

I'm thinking the above implementation is not really an "App Insights issue," more like React/Gatsby, but I can't figure out how to correctly code it.

**Comment by tallman5** [comment]
This works for page tracking:

```
if (typeof window !== "undefined") {
    const appInsights = new ApplicationInsights({
        config: {
            instrumentationKey: process.env.APPINSIGHTS_KEY
        }
    });
    appInsights.loadAppInsights();
    appInsights.trackPageView();
}
```
Now just to make it work for all the other AI functionality

**Comment by chrisbchoi** [comment]
```javascript
import { ApplicationInsights } from "@microsoft/applicationinsights-web"
import {
  ReactPlugin,
  withAITracking,
} from "@microsoft/applicationinsights-react-js"
import { globalHistory } from "@reach/router"

const reactPlugin = new ReactPlugin()
let ai = null
if (typeof window !== "undefined") {
  const ai = new ApplicationInsights({
    config: {
      instrumentationKey: process.env.APPINSIGHTS_KEY,
      extensions: [reactPlugin],
      extensionConfig: {
        [reactPlugin.identifier]: { history: globalHistory },
      },
    },
  })
  ai.loadAppInsights()
  ai.trackPageView()
}
ReactPlugin.prototype.trackEvent = function(event, customProperties) {
  this._analyticsPlugin.trackEvent(event, customProperties)
}

export default Component => withAITracking(reactPlugin, Component)
export const appInsights = ai?.appInsights
export { reactPlugin }
```

the above code changes fixes 
```javascript
gatsby build
```
problem I had. Thanks

**Comment by tallman5** [comment]
@chrisbchoi - I'm still getting an error when building. How does your Layout implement this?
